# Generated by Django 5.0.3 on 2024-04-01 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('fotoFilme', models.ImageField(upload_to='filme_fotos/')),
            ],
        ),
        migrations.AddField(
            model_name='myprofile',
            name='amigos',
            field=models.ManyToManyField(to='myapp.myprofile'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='dataDeNascimento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='fotoPerfil',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='perfil_fotos/'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField()),
                ('comentario', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.filme')),
            ],
        ),
        migrations.AddField(
            model_name='myprofile',
            name='filmes',
            field=models.ManyToManyField(to='myapp.filme'),
        ),
    ]
