# Generated by Django 5.0.3 on 2024-04-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_filme_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='fotoFilme',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='titulo',
        ),
    ]
