# Generated by Django 5.0.3 on 2024-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_filme_ano_remove_filme_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
    ]
