# Generated by Django 5.0.4 on 2024-04-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_filme_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='seguindo',
            field=models.ManyToManyField(related_name='seguidores', to='myapp.myprofile'),
        ),
    ]
