# Generated by Django 5.0.4 on 2024-04-29 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_myprofile_seguindo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='filme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.filme'),
            preserve_default=False,
        ),
    ]
