# Generated by Django 5.0.3 on 2024-07-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_usuariogenerovisto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariogenerovisto',
            name='visto_em',
        ),
    ]
