# Generated by Django 5.0.3 on 2024-07-11 01:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_usuariogenerovisto_visto_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioGeneroVisto',
            new_name='GeneroVisto',
        ),
    ]
